# -*- coding: utf-8 -*-
"""Window_datathon_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-e37o3STjy7KIFEZ9BJoe-HPMG5Ib8h

0. CHUẨN BỊ THƯ VIỆN VÀ DỮ LIỆU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import lightgbm as lgb
from sklearn.linear_model import Ridge
from prophet import Prophet
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import shap
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# Tải dữ liệu
train      = pd.read_csv('sales.csv',             parse_dates=['Date'])
sample_sub = pd.read_csv('sample_submission.csv', parse_dates=['Date'])

train = train.sort_values('Date').reset_index(drop=True)

print(f"Train:  {train['Date'].min().date()} → {train['Date'].max().date()} ({len(train)} rows)")
print(f"Test:   {sample_sub['Date'].min().date()} → {sample_sub['Date'].max().date()} ({len(sample_sub)} rows)")
print(f"\nTrain Revenue: mean={train['Revenue'].mean():,.0f}  std={train['Revenue'].std():,.0f}")
print(f"Train COGS:    mean={train['COGS'].mean():,.0f}  std={train['COGS'].std():,.0f}")

"""1. XÂY DỰNG ĐẶC TRƯNG PHÂN LOẠI CHO DỮ LIỆU"""

# Ngày mồng 1 Tết Âm lịch (dương lịch)
TET_DATES = {
    2012: '2012-01-23',
    2013: '2013-02-10',
    2014: '2014-01-31',
    2015: '2015-02-19',
    2016: '2016-02-08',
    2017: '2017-01-28',
    2018: '2018-02-16',
    2019: '2019-02-05',
    2020: '2020-01-25',
    2021: '2021-02-12',
    2022: '2022-02-01',
    2023: '2023-01-22',
    2024: '2024-02-10',
}

# Lịch khuyến mãi thường niên (trích từ promotions.csv)
# (tên, tháng_bắt_đầu, ngày_bắt_đầu, số_ngày_kéo_dài, discount%, lặp_lại)
PROMO_SCHEDULE = [
    ('spring_sale',    3,  18, 30, 12,   True),   # mỗi năm
    ('mid_year',       6,  23, 29, 18,   True),   # mỗi năm
    ('fall_launch',    8,  30, 32, 10,   True),   # mỗi năm
    ('year_end',      11,  18, 45, 20,   True),   # mỗi năm
    ('urban_blowout',  7,  30, 33, None, 'odd'),  # chỉ năm lẻ
    ('rural_special',  1,  30, 30, 15,   'odd'),  # chỉ năm lẻ
]

# Ngày lễ cố định Việt Nam
VN_FIXED_HOLIDAYS = [
    (1,  1,  'new_year'),
    (3,  8,  'womens_day'),
    (4,  30, 'reunification'),
    (5,  1,  'labor_day'),
    (9,  2,  'national_day'),
    (10, 20, 'vn_womens_day'),
    (11, 11, 'dd_1111'),
    (12, 12, 'dd_1212'),
    (12, 24, 'christmas_eve'),
    (12, 25, 'christmas'),
]

def build_features(dates_input) -> pd.DataFrame:
    """
    Tạo calendar-only features từ cột Date.
    Có thể tính sẵn cho cả train lẫn test ngay từ đầu.
    """
    if isinstance(dates_input, pd.Series):
        dates = pd.DatetimeIndex(dates_input.values)
    else:
        dates = pd.DatetimeIndex(dates_input)

    df = pd.DataFrame({'Date': dates})
    d  = df['Date']

    # ── (a) Calendar cơ bản ──
    df['year']       = d.dt.year
    df['month']      = d.dt.month
    df['day']        = d.dt.day
    df['dow']        = d.dt.dayofweek       # 0=Thứ2, 6=CN
    df['doy']        = d.dt.dayofyear
    df['quarter']    = d.dt.quarter
    df['is_weekend'] = (df['dow'] >= 5).astype(int)
    df['dim']        = d.dt.days_in_month   # số ngày trong tháng

    df['days_to_eom']   = df['dim'] - df['day']    # còn bao nhiêu ngày đến cuối tháng
    df['days_from_som'] = df['day'] - 1             # đã qua bao nhiêu ngày từ đầu tháng

    # ── (b) Edge-of-month — KEY INSIGHT ──
    # Ngày 28-31 cuối tháng cao gấp đôi ngày giữa tháng!
    # Ngày 1-3 đầu tháng cũng cao (pattern lương)
    for k in [1, 2, 3]:
        df[f'is_last{k}']  = (df['days_to_eom'] <= k - 1).astype(int)
        df[f'is_first{k}'] = (df['days_from_som'] <= k - 1).astype(int)

    # ── (c) Trend + Regime ──
    # 3 regime rõ ràng: pre-2019 (cao), 2019 (transition), post-2019 (thấp hơn)
    df['t_days']          = (d - pd.Timestamp('2020-01-01')).dt.days
    df['t_years']         = df['t_days'] / 365.25
    df['regime_pre2019']  = (df['year'] <= 2018).astype(int)
    df['regime_2019']     = (df['year'] == 2019).astype(int)
    df['regime_post2019'] = (df['year'] >= 2020).astype(int)

    # ── (d) Fourier Seasonality ──
    # Biến mùa vụ thành sóng sin/cos → Ridge học được seasonality
    # Annual: 5 harmonics (bắt được pattern năm phức tạp)
    # Weekly: 2 harmonics
    # Monthly: 2 harmonics (bắt được pattern trong tháng)
    TAU = 2 * np.pi
    for k in range(1, 6):
        df[f'sin_y{k}'] = np.sin(TAU * k * df['doy'] / 365.25)
        df[f'cos_y{k}'] = np.cos(TAU * k * df['doy'] / 365.25)
    for k in range(1, 3):
        df[f'sin_w{k}'] = np.sin(TAU * k * df['dow'] / 7.0)
        df[f'cos_w{k}'] = np.cos(TAU * k * df['dow'] / 7.0)
    for k in range(1, 3):
        df[f'sin_m{k}'] = np.sin(TAU * k * (df['day'] - 1) / df['dim'])
        df[f'cos_m{k}'] = np.cos(TAU * k * (df['day'] - 1) / df['dim'])

    # ── (e) Ngày lễ cố định Việt Nam ──
    for (m, dd, name) in VN_FIXED_HOLIDAYS:
        df[f'hol_{name}'] = ((df['month'] == m) & (df['day'] == dd)).astype(int)

    # ── (f) Tết Âm lịch — dùng khoảng cách thay vì flag cố định ──
    # Tết rơi khác ngày mỗi năm → flag tháng 1-2 không bắt được chính xác
    tet_lut = {y: pd.Timestamp(v) for y, v in TET_DATES.items()}

    def nearest_tet_diff(dd):
        cands = [tet_lut.get(dd.year),
                 tet_lut.get(dd.year - 1),
                 tet_lut.get(dd.year + 1)]
        valid = [(dd - c).days for c in cands
                 if c is not None and abs((dd - c).days) <= 60]
        if not valid:
            return 999
        return min(valid, key=abs)

    diffs = np.array([nearest_tet_diff(dd) for dd in d])
    df['tet_days_diff'] = diffs                                          # -60 đến +60
    df['tet_in_7']      = (np.abs(diffs) <= 7).astype(int)
    df['tet_in_14']     = (np.abs(diffs) <= 14).astype(int)
    df['tet_before_7']  = ((diffs >= -7) & (diffs < 0)).astype(int)    # 7 ngày trước Tết
    df['tet_after_7']   = ((diffs > 0) & (diffs <= 7)).astype(int)     # 7 ngày sau Tết
    df['tet_on']        = (diffs == 0).astype(int)

    # ── (g) Black Friday thực sự (thứ Sáu cuối tháng 11) ──
    def is_black_friday(dd):
        if dd.month != 11:
            return 0
        last = pd.Timestamp(year=dd.year, month=11, day=30)
        last_fri = last - pd.Timedelta(days=(last.dayofweek - 4) % 7)
        return int(dd == last_fri)

    df['hol_black_friday'] = [is_black_friday(dd) for dd in d]

    # ── (h) Promo windows ──
    # Mỗi chiến dịch: flag đang trong promo, đã chạy bao lâu, còn bao lâu
    yrs = sorted(set(df['year'].tolist()))
    for (name, sm, sd, dur, disc, recur) in PROMO_SCHEDULE:
        in_prom = np.zeros(len(df), dtype=int)
        since   = np.full(len(df), -1.0)
        until   = np.full(len(df), -1.0)
        for y in range(min(yrs) - 1, max(yrs) + 2):
            if recur == 'odd' and y % 2 == 0:
                continue
            try:
                start = pd.Timestamp(year=y, month=sm, day=sd)
            except Exception:
                continue
            end  = start + pd.Timedelta(days=dur)
            mask = (d >= start) & (d <= end)
            mask_arr = mask.values
            in_prom[mask_arr] = 1
            since[mask_arr]   = (d[mask] - start).dt.days.values
            until[mask_arr]   = (end - d[mask]).dt.days.values
        df[f'promo_{name}']       = in_prom
        df[f'promo_{name}_since'] = since
        df[f'promo_{name}_until'] = until

    # ── (i) Năm lẻ / năm chẵn ──
    # Năm lẻ có Urban Blowout → Q3 biến động khác hẳn
    # 2023=lẻ, 2024=chẵn → quan trọng cho test
    df['is_odd_year'] = (df['year'] % 2).astype(int)

    return df

"""2. PHÂN CHIA TẬP DỮ LIỆU CHO MODEL"""

# ── Tạo features cho TOÀN BỘ (train + test) cùng lúc ──
all_dates  = pd.DatetimeIndex(
    pd.concat([train['Date'], sample_sub['Date']],
              ignore_index=True).values
)
feat_all   = build_features(all_dates)

train_feat = feat_all.iloc[:len(train)].copy().reset_index(drop=True)
test_feat  = feat_all.iloc[len(train):].copy().reset_index(drop=True)

train_feat['Revenue'] = train['Revenue'].values
train_feat['COGS']    = train['COGS'].values

FEATURE_COLS = [c for c in train_feat.columns
                if c not in ['Date', 'Revenue', 'COGS']]

print(f" Features: {len(FEATURE_COLS)} cột")
print(f" Train rows: {len(train_feat)} | Test rows: {len(test_feat)}")
print(f" Không có NaN vì không dùng lag!")
print(f"\nMột số features: {FEATURE_COLS[:10]}")

"""3. SAMPLE WEIGHTING (HIGH-ERA) - VALIDATION FORD"""

# Ưu tiên 2014-2018: vùng seasonality rõ nhất, data sạch nhất
# Downweight 2012-2013 (noisy) và post-2019 (regime mới, level thấp hơn)

years_train = train_feat['Date'].dt.year.values

sample_weight = np.full(len(train_feat), 0.01)
sample_weight[(years_train >= 2014) & (years_train <= 2018)] = 1.0

print(f"High-weight samples (2014-2018): {(sample_weight == 1.0).sum()} ngày")
print(f"Low-weight samples:              {(sample_weight == 0.01).sum()} ngày")

# ── Validation fold ──
# Fold A (primary): train ≤ 2021, val = 2022
# Lý do: 2022 gần nhất với phân phối test 2023
val_mask_A   = (train_feat['Date'].dt.year == 2022).values
train_mask_A = ~val_mask_A

X_all   = train_feat[FEATURE_COLS].values
y_rev   = train['Revenue'].values
y_cogs  = train['COGS'].values
y_rev_log  = np.log(y_rev)
y_cogs_log = np.log(y_cogs)
X_test  = test_feat[FEATURE_COLS].values

print(f"\nFold A — Train: {train_mask_A.sum()} rows | Val: {val_mask_A.sum()} rows")

"""3. HUẤN LUYỆN 3 MODEL"""

# ── M1: Ridge ──
def train_ridge(X, y, alpha=3.0):
    """Train Ridge trên log-space với z-score normalization"""
    mu    = X.mean(axis=0)
    sigma = X.std(axis=0)
    sigma[sigma == 0] = 1.0   # tránh chia 0
    Xs    = (X - mu) / sigma
    model = Ridge(alpha=alpha, random_state=42)
    model.fit(Xs, y)
    return model, mu, sigma

def predict_ridge(model, mu, sigma, X):
    return model.predict((X - mu) / sigma)

# Train Revenue
ridge_rev, mu_r, sigma_r = train_ridge(
    X_all[train_mask_A], y_rev_log[train_mask_A]
)
val_pred_ridge_rev = np.exp(predict_ridge(ridge_rev, mu_r, sigma_r, X_all[val_mask_A]))
p_ridge_rev_test   = np.exp(predict_ridge(ridge_rev, mu_r, sigma_r, X_test))

# Train COGS
ridge_cog, mu_rc, sigma_rc = train_ridge(
    X_all[train_mask_A], y_cogs_log[train_mask_A]
)
val_pred_ridge_cog = np.exp(predict_ridge(ridge_cog, mu_rc, sigma_rc, X_all[val_mask_A]))
p_ridge_cog_test   = np.exp(predict_ridge(ridge_cog, mu_rc, sigma_rc, X_test))

mae_r = mean_absolute_error(y_rev[val_mask_A], val_pred_ridge_rev)
r2_r  = r2_score(y_rev[val_mask_A], val_pred_ridge_rev)
print(f"Ridge Revenue — Val MAE: {mae_r:,.0f} | R²: {r2_r:.4f}")

# ── M2: LIGHTGBM ──
LGB_PARAMS = dict(
    objective='regression',
    metric='mae',
    learning_rate=0.03,
    num_leaves=63,
    min_data_in_leaf=30,
    feature_fraction=0.85,
    bagging_fraction=0.85,
    bagging_freq=5,
    lambda_l2=1.0,
    seed=42,
    verbosity=-1,
)

def train_lgb_two_stage(X_tr, y_tr, w_tr, X_val, y_val, params, label=""):
    """
    2 giai đoạn:
    1. Early stopping để tìm best_iteration
    2. Retrain toàn bộ với best_iteration
    """
    # Giai đoạn 1: early stopping
    bo_es = lgb.train(
        params,
        lgb.Dataset(X_tr, y_tr, weight=w_tr),
        num_boost_round=5000,
        valid_sets=[lgb.Dataset(X_val, y_val)],
        callbacks=[
            lgb.early_stopping(300, verbose=False),
            lgb.log_evaluation(0)
        ]
    )
    best_iter = bo_es.best_iteration
    print(f"  {label} best_iteration: {best_iter}")

    # Giai đoạn 2: retrain toàn bộ
    X_full = np.vstack([X_tr, X_val])
    y_full = np.concatenate([y_tr, y_val])
    w_full = np.concatenate([w_tr, w_tr[-len(X_val):]])  # dùng weight tương tự cho val
    bo_final = lgb.train(
        params,
        lgb.Dataset(X_full, y_full, weight=w_full),
        num_boost_round=best_iter
    )
    return bo_final, best_iter

# Revenue base
w_train_A = sample_weight[train_mask_A]

lgb_base_rev, _ = train_lgb_two_stage(
    X_all[train_mask_A], y_rev_log[train_mask_A], w_train_A,
    X_all[val_mask_A],   y_rev_log[val_mask_A],
    LGB_PARAMS, label="LGB-base-Revenue"
)

val_pred_lgb_rev = np.exp(lgb_base_rev.predict(X_all[val_mask_A]))
p_lgb_rev_test   = np.exp(lgb_base_rev.predict(X_test))

# COGS base
lgb_base_cog, _ = train_lgb_two_stage(
    X_all[train_mask_A], y_cogs_log[train_mask_A], w_train_A,
    X_all[val_mask_A],   y_cogs_log[val_mask_A],
    LGB_PARAMS, label="LGB-base-COGS"
)
val_pred_lgb_cog = np.exp(lgb_base_cog.predict(X_all[val_mask_A]))
p_lgb_cog_test   = np.exp(lgb_base_cog.predict(X_test))

mae_l = mean_absolute_error(y_rev[val_mask_A], val_pred_lgb_rev)
r2_l  = r2_score(y_rev[val_mask_A], val_pred_lgb_rev)
print(f"LGB Base Revenue — Val MAE: {mae_l:,.0f} | R²: {r2_l:.4f}")

# ── M3: PROPHET ──
# Prophet chỉ train trên 2020-2022 (post-regime)
# Lý do: trend pre-2019 rất khác → làm lệch extrapolation
promo_cols = [c for c in FEATURE_COLS if c.startswith('promo_')]

train_post2019 = train_feat[train_feat['Date'] >= '2020-01-01'].copy()

prophet_df = pd.DataFrame({
    'ds': train_post2019['Date'],
    'y' : np.log(train_post2019['Revenue'].values)
})
for col in promo_cols:
    prophet_df[col] = train_post2019[col].values

m_prophet_rev = Prophet(
    yearly_seasonality=True,
    weekly_seasonality=True,
    daily_seasonality=False,
    seasonality_mode='multiplicative',
    changepoint_prior_scale=0.05
)
for col in promo_cols:
    m_prophet_rev.add_regressor(col)
m_prophet_rev.fit(prophet_df)

# Predict test
future_df = pd.DataFrame({'ds': sample_sub['Date']})
for col in promo_cols:
    future_df[col] = test_feat[col].values
p_prophet_rev_test = np.exp(m_prophet_rev.predict(future_df)['yhat'].values)
p_prophet_rev_test = np.maximum(p_prophet_rev_test, 0)

# Predict val (để so sánh)
val_df_prophet = pd.DataFrame({'ds': train_feat[val_mask_A]['Date']})
for col in promo_cols:
    val_df_prophet[col] = train_feat[val_mask_A][col].values
val_pred_prophet_rev = np.exp(m_prophet_rev.predict(val_df_prophet)['yhat'].values)

# COGS Prophet
prophet_cog_df = pd.DataFrame({
    'ds': train_post2019['Date'],
    'y' : np.log(train_post2019['COGS'].values)
})
for col in promo_cols:
    prophet_cog_df[col] = train_post2019[col].values

m_prophet_cog = Prophet(
    yearly_seasonality=True, weekly_seasonality=True,
    daily_seasonality=False, seasonality_mode='multiplicative',
    changepoint_prior_scale=0.05
)
for col in promo_cols:
    m_prophet_cog.add_regressor(col)
m_prophet_cog.fit(prophet_cog_df)
p_prophet_cog_test = np.exp(m_prophet_cog.predict(future_df)['yhat'].values)
p_prophet_cog_test = np.maximum(p_prophet_cog_test, 0)

mae_p = mean_absolute_error(y_rev[val_mask_A], val_pred_prophet_rev)
r2_p  = r2_score(y_rev[val_mask_A], val_pred_prophet_rev)
print(f"Prophet Revenue — Val MAE: {mae_p:,.0f} | R²: {r2_p:.4f}")

"""4. NÂNG CẤP MODEL VỚI Q-SPECIALISTS & ENSEMBLE 3 TẦNG"""

# Q-SPECIALISTS (4 models × 2 targets)
Q_train = train_feat['Date'].dt.quarter.values
Q_test  = sample_sub['Date'].dt.quarter.values

specialists_rev = {}
specialists_cog = {}

for target_q in [1, 2, 3, 4]:
    print(f"  Training Spec-Q{target_q}...")

    # Sample weight: base high_era + boost 2× cho quý target
    w_spec = sample_weight.copy()
    w_spec[Q_train == target_q] *= 2.0

    w_spec_A = w_spec[train_mask_A]

    # Revenue specialist
    spec_rev, _ = train_lgb_two_stage(
        X_all[train_mask_A], y_rev_log[train_mask_A], w_spec_A,
        X_all[val_mask_A],   y_rev_log[val_mask_A],
        LGB_PARAMS, label=f"  Spec-Q{target_q}-Rev"
    )
    specialists_rev[target_q] = np.exp(spec_rev.predict(X_test))

    # COGS specialist
    spec_cog, _ = train_lgb_two_stage(
        X_all[train_mask_A], y_cogs_log[train_mask_A], w_spec_A,
        X_all[val_mask_A],   y_cogs_log[val_mask_A],
        LGB_PARAMS, label=f"  Spec-Q{target_q}-Cog"
    )
    specialists_cog[target_q] = np.exp(spec_cog.predict(X_test))

# Ghép predictions theo đúng quý của từng ngày test
p_spec_rev_test = np.zeros(len(sample_sub))
p_spec_cog_test = np.zeros(len(sample_sub))

for q in [1, 2, 3, 4]:
    mask = Q_test == q
    p_spec_rev_test[mask] = specialists_rev[q][mask]
    p_spec_cog_test[mask] = specialists_cog[q][mask]

print("Q-Specialists xong")

# ENSEMBLE 3 TẦNG
# Tham số ensemble (theo tài liệu AIO — có thể tune sau)
ALPHA = 0.60   # tỉ lệ specialist trong LGB blend (0=chỉ base, 1=chỉ specialist)
W_RIDGE   = 0.10
W_PROPHET = 0.10
W_LGB     = 0.80

# Calibration — điều chỉnh level từ vùng học sang vùng test
# Tune bằng cách nộp nhiều giá trị lên Kaggle
CR = 1.30   # Revenue calibration
CC = 1.30   # COGS calibration

# ── Tầng 1: Hợp nhất LGB nội bộ ──
lgb_blend_rev = ALPHA * p_spec_rev_test + (1 - ALPHA) * p_lgb_rev_test
lgb_blend_cog = ALPHA * p_spec_cog_test + (1 - ALPHA) * p_lgb_cog_test

# ── Tầng 2: Hợp nhất 3 họ model ──
raw_rev = (W_RIDGE   * p_ridge_rev_test +
           W_PROPHET * p_prophet_rev_test +
           W_LGB     * lgb_blend_rev)

raw_cog = (W_RIDGE   * p_ridge_cog_test +
           W_PROPHET * p_prophet_cog_test +
           W_LGB     * lgb_blend_cog)

# ── Tầng 3: Calibration ──
final_rev = CR * raw_rev
final_cog = CC * raw_cog

# Đảm bảo không âm
final_rev = np.maximum(final_rev, 0)
final_cog = np.maximum(final_cog, 0)

print(f"Revenue — mean: {final_rev.mean():,.0f}  min: {final_rev.min():,.0f}  max: {final_rev.max():,.0f}")
print(f"COGS    — mean: {final_cog.mean():,.0f}  min: {final_cog.min():,.0f}  max: {final_cog.max():,.0f}")
print(f"Train Revenue mean: {train['Revenue'].mean():,.0f}")
print(f"Ratio test/train:   {final_rev.mean()/train['Revenue'].mean():.3f} (lý tưởng: 0.8–1.3)")

y_val_rev = y_rev[val_mask_A]

models_val = {
    'Ridge':   val_pred_ridge_rev,
    'LGB':     val_pred_lgb_rev,
    'Prophet': val_pred_prophet_rev,
}

for name, preds in models_val.items():
    mae = mean_absolute_error(y_val_rev, preds)
    r2  = r2_score(y_val_rev, preds)
    print(f"{name:10s}  MAE={mae:>12,.0f}  R²={r2:.4f}")

print("="*50)

"""5. DỰ BÁO DOANH THU CHO TẬP TEST - TẠO SUBMISSION"""

# TẠO SUBMISSION FILE
submission = pd.DataFrame({
    'Date'   : sample_sub['Date'].dt.strftime('%Y-%m-%d'),
    'Revenue': np.round(final_rev, 2),
    'COGS'   : np.round(final_cog, 2),
})

submission.to_csv('submission.csv', index=False)
print(" submission.csv đã lưu!")
print(submission.head(10).to_string(index=False))

# VERIFY SUBMISSION
sub_check = pd.read_csv('submission.csv')
ref       = pd.read_csv('sample_submission.csv')

print("\n── Verification ──")
ok = True

if len(sub_check) != len(ref):
    print(" Số dòng không khớp!"); ok = False
else:
    print(f" Số dòng: {len(sub_check)}")

if list(sub_check.columns) != ['Date', 'Revenue', 'COGS']:
    print(" Cột không khớp!"); ok = False
else:
    print(f" Cột: Date, Revenue, COGS")

if (sub_check['Revenue'] < 0).any():
    print(" Có Revenue âm!"); ok = False
else:
    print(f" Revenue: không âm")

if (sub_check['COGS'] < 0).any():
    print(" Có COGS âm!"); ok = False
else:
    print(f" COGS: không âm")

if sub_check['Revenue'].isnull().any():
    print(" Có Revenue null!"); ok = False
else:
    print(f" Revenue: không null")

if ok:
    print("\n Không có lỗi! ")
else:
    print("\n  Có lỗi, kiểm tra lại!")

"""5. TRỰC QUAN HÓA KẾT QUẢ DỰ BÁO"""

fig, axes = plt.subplots(1, 1, figsize=(14, 6))

# Plot Revenue
train_tail = train[train['Date'] >= '2022-01-01']
axes.plot(train_tail['Date'], train_tail['Revenue'],
             color='steelblue', lw=1.2, label='Train (2022)')
axes.plot(sample_sub['Date'], final_rev,
             color='tomato', lw=1.2, ls='--', label='Predicted Revenue')
axes.axvline(pd.Timestamp('2023-01-01'), color='gray',
                ls=':', lw=1.5, label='Train/Test boundary')
axes.set_title('Revenue Forecast 2023–2024 (Ensemble)', fontweight='bold')
axes.set_xlabel('Date')
axes.set_ylabel('Revenue (VND)')
axes.legend()
axes.yaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x, _: f'{x/1e6:.0f}M'))

plt.tight_layout()
plt.savefig('forecast_revenue.png', dpi=150)
plt.show()
print(" Đã lưu forecast_revenue.png")

"""4. PHÂN TÍCH SHAP ĐỂ GIẢI THÍCH MÔ HÌNH"""

# SHAP cho mô hình Revenue (LightGBM)
# Khởi tạo explainer cho mô hình cây LightGBM
explainer_rev = shap.TreeExplainer(lgb_base_rev)

# Tính toán SHAP values trên tập huấn luyện (hoặc tập validation)
# Chúng ta sử dụng X_all[train_mask_A] là tập dữ liệu training đã dùng cho lgb_base_rev
shap_values_rev = explainer_rev.shap_values(X_all[train_mask_A])

# Trực quan hóa SHAP Summary Plot (Beeswarm plot)
# Plot này hiển thị tổng quan về tầm quan trọng của các đặc trưng và hướng tác động của chúng
# Mỗi điểm trên biểu đồ là một Shapley value cho một đặc trưng và một mẫu cụ thể.
# Màu sắc (đỏ/xanh) cho biết giá trị của đặc trưng đó (cao/thấp).
# Vị trí trên trục x biểu thị tác động của đặc trưng lên đầu ra của mô hình.
plt.figure(figsize=(12, 8))
shap.summary_plot(shap_values_rev, X_all[train_mask_A], feature_names=FEATURE_COLS, show=False)
plt.title('SHAP Summary Plot for LightGBM Revenue Model (Log-transformed)')
plt.tight_layout()
plt.show()

print("✅ SHAP Summary Plot for LightGBM Revenue Model đã được tạo.")
